name: Automated API tests using Postman CLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 
  
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Check version Newman and Node
        run: |
          newman --version
          node --version
      
      - name: Newman Reporter      
        run: sudo npm install -g newman-reporter-htmlextra

      - name: Executar collection
        run: newman run ./server_rest-ci.json -e ./server_rest-env.json --reporters cli, -r htmlextra --reporter-htmlextra-export ./results/Report.html

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ./results/Report.html     
          
          
